# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from grpc_generated import importer_config_pb2 as importer__config__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in importer_config_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ImporterServiceStub(object):
    """Simplified Importer Service for Coinbase
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.StartImport = channel.unary_unary(
                '/coinbase_importer.ImporterService/StartImport',
                request_serializer=importer__config__pb2.StartImportRequest.SerializeToString,
                response_deserializer=importer__config__pb2.ImportResponse.FromString,
                _registered_method=True)
        self.StopImport = channel.unary_unary(
                '/coinbase_importer.ImporterService/StopImport',
                request_serializer=importer__config__pb2.StopImportRequest.SerializeToString,
                response_deserializer=importer__config__pb2.ImportResponse.FromString,
                _registered_method=True)
        self.GetStatus = channel.unary_unary(
                '/coinbase_importer.ImporterService/GetStatus',
                request_serializer=importer__config__pb2.GetStatusRequest.SerializeToString,
                response_deserializer=importer__config__pb2.GetStatusResponse.FromString,
                _registered_method=True)
        self.GetConfig = channel.unary_unary(
                '/coinbase_importer.ImporterService/GetConfig',
                request_serializer=importer__config__pb2.GetConfigRequest.SerializeToString,
                response_deserializer=importer__config__pb2.GetConfigResponse.FromString,
                _registered_method=True)
        self.SetConfig = channel.unary_unary(
                '/coinbase_importer.ImporterService/SetConfig',
                request_serializer=importer__config__pb2.SetConfigRequest.SerializeToString,
                response_deserializer=importer__config__pb2.SetConfigResponse.FromString,
                _registered_method=True)


class ImporterServiceServicer(object):
    """Simplified Importer Service for Coinbase
    """

    def StartImport(self, request, context):
        """Start an import for a specific source (e.g., "app", "pro")
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StopImport(self, request, context):
        """Stop an import for a specific source
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetStatus(self, request, context):
        """Get current status of the importer
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetConfig(self, request, context):
        """Get current configuration
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetConfig(self, request, context):
        """Update configuration
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ImporterServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'StartImport': grpc.unary_unary_rpc_method_handler(
                    servicer.StartImport,
                    request_deserializer=importer__config__pb2.StartImportRequest.FromString,
                    response_serializer=importer__config__pb2.ImportResponse.SerializeToString,
            ),
            'StopImport': grpc.unary_unary_rpc_method_handler(
                    servicer.StopImport,
                    request_deserializer=importer__config__pb2.StopImportRequest.FromString,
                    response_serializer=importer__config__pb2.ImportResponse.SerializeToString,
            ),
            'GetStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.GetStatus,
                    request_deserializer=importer__config__pb2.GetStatusRequest.FromString,
                    response_serializer=importer__config__pb2.GetStatusResponse.SerializeToString,
            ),
            'GetConfig': grpc.unary_unary_rpc_method_handler(
                    servicer.GetConfig,
                    request_deserializer=importer__config__pb2.GetConfigRequest.FromString,
                    response_serializer=importer__config__pb2.GetConfigResponse.SerializeToString,
            ),
            'SetConfig': grpc.unary_unary_rpc_method_handler(
                    servicer.SetConfig,
                    request_deserializer=importer__config__pb2.SetConfigRequest.FromString,
                    response_serializer=importer__config__pb2.SetConfigResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'coinbase_importer.ImporterService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('coinbase_importer.ImporterService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ImporterService(object):
    """Simplified Importer Service for Coinbase
    """

    @staticmethod
    def StartImport(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/coinbase_importer.ImporterService/StartImport',
            importer__config__pb2.StartImportRequest.SerializeToString,
            importer__config__pb2.ImportResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StopImport(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/coinbase_importer.ImporterService/StopImport',
            importer__config__pb2.StopImportRequest.SerializeToString,
            importer__config__pb2.ImportResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/coinbase_importer.ImporterService/GetStatus',
            importer__config__pb2.GetStatusRequest.SerializeToString,
            importer__config__pb2.GetStatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetConfig(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/coinbase_importer.ImporterService/GetConfig',
            importer__config__pb2.GetConfigRequest.SerializeToString,
            importer__config__pb2.GetConfigResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetConfig(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/coinbase_importer.ImporterService/SetConfig',
            importer__config__pb2.SetConfigRequest.SerializeToString,
            importer__config__pb2.SetConfigResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
